@extends('layouts.app')

@section('content')
    <x-common.page-breadcrumb pageTitle="New campaign" />
    <div class="mx-auto max-w-3xl rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03] md:p-8">
        <h2 class="text-xl font-semibold text-gray-800 dark:text-white/90">Create a campaign</h2><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">Set the brief and budget. You can staff the roster after creation.</p>
        <form method="POST" action="{{ route('campaigns.store') }}" class="mt-7 space-y-5">@csrf
            <div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Campaign name</label><input name="name" value="{{ old('name') }}" required class="h-11 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"></div>
            <div class="grid gap-5 sm:grid-cols-2"><div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Objective</label><input name="objective" value="{{ old('objective') }}" placeholder="Awareness, conversion, retention…" class="h-11 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"></div><div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Budget</label><input name="budget_total" type="number" min="0" step="0.01" value="{{ old('budget_total', 0) }}" required class="h-11 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"></div></div>
            <div class="grid gap-5 sm:grid-cols-2"><div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Stage</label><select name="stage" class="h-11 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90">@foreach($stages as $key => $label)<option value="{{ $key }}" @selected(old('stage', 'brief') === $key)>{{ $label }}</option>@endforeach</select></div><div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Status</label><select name="status" class="h-11 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90">@foreach($statuses as $key => $label)<option value="{{ $key }}" @selected(old('status', 'draft') === $key)>{{ $label }}</option>@endforeach</select></div></div>
            <div class="grid gap-5 sm:grid-cols-2"><div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Starts</label><input name="starts_at" type="date" value="{{ old('starts_at') }}" class="h-11 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"></div><div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Ends</label><input name="ends_at" type="date" value="{{ old('ends_at') }}" class="h-11 w-full rounded-lg border border-gray-300 bg-transparent px-3 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90"></div></div>
            <div><label class="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">Brief</label><textarea name="brief" rows="6" class="w-full rounded-lg border border-gray-300 bg-transparent p-3 text-sm dark:border-gray-700 dark:bg-gray-900 dark:text-white/90">{{ old('brief') }}</textarea></div>
            <div class="flex justify-end gap-3"><a href="{{ route('campaigns') }}" class="rounded-lg border border-gray-300 px-4 py-2.5 text-sm font-medium text-gray-700 dark:border-gray-700 dark:text-gray-300">Cancel</a><button class="rounded-lg bg-brand-500 px-5 py-2.5 text-sm font-medium text-white hover:bg-brand-600">Create campaign</button></div>
        </form>
    </div>
@endsection